# configuration for https://codecov.io
ignore:
  - "sacroml/config"
  - "sacroml/main.py"
  - "sacroml/safemodel/classifiers/new_model_template.py"
  - "examples"
  - "setup.py"
  - "user_stories"
  - "tests"  # Exclude test files from coverage calculation

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
